### ISSUE TITLE
MSFT incompatibilities with dbt-adapter-tests

### ISSUE THREAD

**Issue by swanderz** [fishtown-analytics/dbt-adapter-tests#7]
see this draft PR: https://github.com/fishtown-analytics/dbt/pull/2790
not sure how to make this work without changing `dbt-core`... would love some ideas on workarounds: both short- and long-term.

**Comment by jtcohen6** [comment]
Right on, @swanderz. We implemented `timestamp_add_sql` and `get_rows_different_sql` as adapter methods for exactly this reason, so that you can override them in plugins.

See:
- BigQuery redefines `timestamp_add_sql` [here](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/plugins/bigquery/dbt/adapters/bigquery/impl.py#L835) and adapts `get_rows_different_sql` [here](https://github.com/fishtown-analytics/dbt/blob/dev/kiyoshi-kuromiya/plugins/bigquery/dbt/adapters/bigquery/impl.py#L821)
- Spark redefines `get_rows_different_sql` [here](https://github.com/fishtown-analytics/dbt-spark/blob/7b3ac5b62d7a75b0325eabcd9564df38cef16a46/dbt/adapters/spark/impl.py#L271)

**Comment by swanderz** [comment]
passing all the adapter tests now (except for incremental & ephemeral, which we haven't touched yet)!

![](https://media.giphy.com/media/zcCGBRQshGdt6/giphy.gif)

**Comment by jtcohen6** [comment]
Thanks for testing this out @swanderz!! I'm going to open issues in a bunch more repos :))
